type: sft
micro_batch_size: 1
min_iterations: 12
exit_iteration: 12
#activation_checkpoint_cpu_offload: true
#tiled_mlp_compute: true
sequence_parallel_size: 1

arctic_moe: false
expert_parallel_size: 1

deepspeed:
  zero_optimization:
    stage: 2
    # offload_optimizer:
    #   device: cpu
    # offload_param:
    #   device: cpu
    #overlap_comm: false
    #reduce_bucket_size: 5e10
  #seq_parallel_communication_data_type: bf16

optimizer:
  type: fused_adam
  learning_rate: 0.00001

model:
  type: "liger"
  arch_variant: moe-dense-equivalent
  name_or_path: Qwen/Qwen3-30B-A3B-Instruct-2507
  #name_or_path: snake7gun/tiny-random-qwen3moe
  #name_or_path: DavidAU/Qwen3-MOE-4x0.6B-2.4B-Writing-Thunder
  #name_or_path: DavidAU/Qwen3-MOE-6x1.7B-10.2B-Shining-Madness-Uncensored
  # hf_config_kwargs:
  #   #num_hidden_layers: 48 #
  #   num_hidden_layers: 24 #

  attn_implementation: flash_attention_2
  #attn_implementation: sdpa

data:
  sources:
  #  - HuggingFaceH4/ultrachat_200k
    - HuggingFaceH4/ultrachat_200k:train[:10000]
  cache_dir: /data-fast/data-cache/stas
  # num_proc: 16
  dl_num_workers: 1

  max_length: 16_000 # 32k in the moe equivalent because of the num of experts mapping
#  max_length: 1024
#  max_length: 132_000
#  max_length: 400_000

wandb:
  enable: true
  #enable: false
  project: arctic-moe
  name: dp8-ep1-dens-z2-Qwen3-30B

logger:
  level: WARNING
#  level: INFO

  output_dir: "logs"
  #file_output_ranks: [0,1]
  print_output_ranks: [0,1,2,3,4,5,6,7]
