type: sft
micro_batch_size: 1
min_iterations: 300
exit_iteration: 300
activation_checkpoint_cpu_offload: true
tiled_mlp_compute: true

sequence_parallel_size: 16
deepspeed:
  zero_optimization:
    stage: 3
    offload_optimizer:
      device: cpu
  seq_parallel_communication_data_type: bf16

optimizer:
  type: cpu_adam
  learning_rate: 0.00001

model:
  type: "liger"
  name_or_path: meta-llama/Llama-3.1-70B-Instruct

  attn_implementation: flash_attention_2
  #attn_implementation: sdpa

data:
  sources:
    - HuggingFaceH4/ultrachat_200k
  #  - HuggingFaceH4/ultrachat_200k:train[:5000]
  cache_dir: data-cache
  
  dl_num_workers: 1

#  max_length: 1_000_000 # ok 37
  max_length: 1_200_000
#  max_length: 1_500_000 # cpu oom NV 44.04 GB
#  max_length: 1_6000_000 # gpu oom
#  max_length: 2_000_000 # cpu oom NV 50.65 GB
#  max_length: 3_000_000 # cpu oom

wandb:
#  enable: true
  enable: false
  project: "ulysses"
  name: "dp1-sp32-llama-8b"

# mem_profiler: e2e
# mem_profiler_max_entries: 1_000_000_000
# mem_profiler_dir: mem-prof-4n-8b

logger:
  level: WARNING
#  level: INFO

  output_dir: "logs"
  #file_output_ranks: [0,1]
  print_output_ranks: [0,1,2,3,4,5,6,7]
