type: sft
micro_batch_size: 1
min_iterations: 10
exit_iteration: 10
activation_checkpoint_cpu_offload: true
tiled_mlp_compute: true

sequence_parallel_size: 64
deepspeed:
  zero_optimization:
    stage: 3
    offload_optimizer:
      device: cpu
  seq_parallel_communication_data_type: bf16

optimizer:
  type: cpu_adam
  learning_rate: 0.00001

model:
  type: "liger"
  name_or_path: Qwen/Qwen3-32B
  #name_or_path: Qwen/Qwen3-4B

  attn_implementation: flash_attention_2
  #attn_implementation: sdpa

data:
  sources:
    - HuggingFaceH4/ultrachat_200k
  #  - HuggingFaceH4/ultrachat_200k:train[:5000]
  cache_dir: /data-fast/data-cache/stas
  # num_proc: 1
  dl_num_workers: 1

#  max_length: 32000 #
  max_length: 15_000_000 # NV 71.00 GB
#  max_length: 16_000_000 # loss=nan, NV 74.79 GB


# mem_profiler: e2e
# mem_profiler_max_entries: 1_000_000_000
# mem_profiler_dir: mem-prof-4n-70b

wandb:
#  enable: true
  enable: false
  project: "ulysses"
  name: "dp1-sp32-llama-70b"


logger:
  level: WARNING
#  level: INFO

  output_dir: "logs"
  #file_output_ranks: [0,1]
  print_output_ranks: [0,1,2,3,4,5,6,7]
