type: sft
micro_batch_size: 1
min_iterations: 40
exit_iteration: 40
activation_checkpoint_cpu_offload: true
tiled_mlp_compute: true

sequence_parallel_size: 32
deepspeed:
  zero_optimization:
    stage: 3
    offload_optimizer:
      device: cpu
  seq_parallel_communication_data_type: bf16

optimizer:
  type: cpu_adam
  learning_rate: 0.00001

model:
  type: "liger"
  name_or_path: meta-llama/Llama-3.1-70B-Instruct

  attn_implementation: flash_attention_2
  #attn_implementation: sdpa

data:
  sources:
    - HuggingFaceH4/ultrachat_200k
  #  - HuggingFaceH4/ultrachat_200k:train[:5000]
  cache_dir: data-cache
  
  dl_num_workers: 1


#  max_length: 750000 #  24GB
#  max_length: 1_000_000 # 25GB
#  max_length: 1_600_000
#  max_length: 2_000_000
#  max_length: 3_000_000 # 40GB
  max_length: 4_000_000 # NV 47.70 GB - but at the brink of cpu-oom!
#  max_length: 4_500_000 # cpu-oom iter2 @ 1900GiB
#  max_length: 5_000_000 # cpu-oom iter2
#  max_length: 5_100_000 # cpu-oom

#  max_length: 8_000_000 # nope


# mem_profiler: e2e
# mem_profiler_max_entries: 1_000_000_000
# mem_profiler_dir: mem-prof-4n-70b

wandb:
#  enable: true
  enable: false
  project: "ulysses"
  name: "dp1-sp32-llama-70b"


logger:
  level: WARNING
#  level: INFO

  output_dir: "logs"
  #file_output_ranks: [0,1]
  print_output_ranks: [0,1,2,3,4,5,6,7]
