type: sft
micro_batch_size: 2
epochs: 1
gradient_accumulation_steps: 1
model:
  type: liger
  name_or_path: meta-llama/Llama-3.1-8B-Instruct
  attn_implementation: flash_attention_2
deepspeed:
  zero_optimization:
    stage: 3
wandb:
  enable: true
  project: arctic-excot
  name: arctic-excot-sft
data:
  sources:
    - /data-fast/excot_sft
  use_data_cache: true
  cache_processed_data: true
  cache_dir: /data-fast/data-cache
  num_proc: 16
  max_length: 8192
logger:
  level: WARNING
  output_dir: "./"
  file_output_ranks: [0]
scheduler:
  name: 'linear'
  warmup_ratio: 0.0
optimizer:
  betas: [0.9,0.999]
  weight_decay: 0.1
  lr: 1e-5
checkpoint:
  - type: huggingface
    save_every_n_steps: 10000
    output_dir: /data/sft-llama-8b
    save_end_of_training: true
