type: arctic-lstm-speculator
micro_batch_size: 16
gradient_accumulation_steps: 16
train_iters: 3000
model:
  name_or_path: lmsys/gpt-oss-120b-bf16
  disable_activation_checkpoint: true
  method: sum_lstm
  proj_dim: 4096
  emb_dim: 4096
  speculator_width: 4096
  speculator_tie_weights: true
  speculator_scale_input: true
  tie_lstm_embs: true
  n_speculator_heads: 3
tokenizer:
  name_or_path: openai/gpt-oss-120b
deepspeed:
  zero_optimization:
    stage: 3
    allgather_bucket_size: 500000000
    stage3_param_persistence_threshold: 10000
    stage3_max_live_parameters: 30000000
    stage3_prefetch_bucket_size: 500000000
    reduce_bucket_size: 250000000
    memory_efficient_linear: true
data:
  sources:
    - type: huggingface
      name_or_path: oss_120b_data
      process: false
  cache_dir: data-cache-oss-120b
  num_proc: 16
  disable_post_load_callbacks: true
logger:
  output_dir: "./"
  file_output_ranks: [0]
scheduler:
  name: cosine
  warmup_ratio: 0.05
optimizer:
  betas: [0.9,0.999]
  weight_decay: 0.1
  lr: 1e-3
checkpoint:
  - type: arctic-lstm-speculator
    save_end_of_training: true
    output_dir: spec-decode-oss-120b
