type: swiftkv
code: ../train.py
micro_batch_size: 1
epochs: 1
gradient_accumulation_steps: 1
sequence_parallel_size: 8
logits_loss_temp: 2.0
hidden_loss_layer: -2
model:
  name_or_path: meta-llama/Llama-3.1-8B-Instruct
  num_key_value_layers: 16
  key_value_group_size: 1
  attn_implementation: flash_attention_2
deepspeed:
  zero_optimization:
    stage: 2
data:
  sources:
    - type: huggingface_instruct
      name_or_path: Open-Orca/OpenOrca
      sample_count: 1000000
    - type: huggingface_instruct
      name_or_path: nvidia/AceMath-Instruct-Training-Data
      split: general_sft_stage2
      sample_count: 1000000
      kwargs:
        verification_mode: no_checks
    - type: huggingface_instruct
      name_or_path: lmsys/lmsys-chat-1m
      sample_count: 1000000
    - THUDM/LongAlign-10k
    - Yukang/LongAlpaca-12k
    - type: ProjectGutenbergSFT
      name_or_path: manu/project_gutenberg
      split: en
      sample_count: 2400
    - type: ProjectGutenbergSFT
      name_or_path: manu/project_gutenberg
      split: fr
      sample_count: 1200
    - type: ProjectGutenbergSFT
      name_or_path: manu/project_gutenberg
      split: de
      sample_count: 1200
    - type: ProjectGutenbergSFT
      name_or_path: manu/project_gutenberg
      split: es
      sample_count: 800
    - type: ProjectGutenbergSFT
      name_or_path: manu/project_gutenberg
      split: nl
      sample_count: 800
    - type: ProjectGutenbergSFT
      name_or_path: manu/project_gutenberg
      split: it
      sample_count: 640
    - type: ProjectGutenbergSFT
      name_or_path: manu/project_gutenberg
      split: pt
      sample_count: 640
    - type: ProjectGutenbergSFT
      name_or_path: manu/project_gutenberg
      split: zh
      sample_count: 320
  cache_dir: /data-fast/data-cache
  num_proc: 16
  max_length: 196608  # 50% longer than 131072
  always_max_length: true
  mask_inputs: true
  drop_last: true
  fuse_positions_prob: 0.1
logger:
  level: INFO
  output_dir: "./"
  file_output_ranks: [0]
scheduler:
  warmup_ratio: 0.05
optimizer:
  betas: [0.9,0.999]
  weight_decay: 0.0
  lr: 0.0002
checkpoint:
  - type: huggingface
    save_every_n_epochs: 1
    output_dir: /checkpoint/llama-3.1-swiftkv-8b-instruct-long
    save_end_of_training: true
