type: swiftkv
code: ../train.py
micro_batch_size: 1
epochs: 1
gradient_accumulation_steps: 1
logits_loss_temp: 2.0
hidden_loss_layer: -2
model:
  name_or_path: meta-llama/Llama-3.1-405B-Instruct
  num_key_value_layers: 63
  key_value_group_size: 1
  attn_implementation: flash_attention_2
deepspeed:
  zero_optimization:
    stage: 3
data:
  sources:
    - type: huggingface_instruct
      name_or_path: Open-Orca/OpenOrca
      sample_count: 500000
    - type: huggingface_instruct
      name_or_path: nvidia/AceMath-Instruct-Training-Data
      split: general_sft_stage2
      sample_count: 500000
      kwargs:
        verification_mode: no_checks
    - type: huggingface_instruct
      name_or_path: lmsys/lmsys-chat-1m
      sample_count: 500000
  cache_dir: /data-fast/data-cache
  num_proc: 16
  max_length: 8192
logger:
  level: INFO
  output_dir: "./"
  file_output_ranks: [0]
scheduler:
  warmup_ratio: 0.05
optimizer:
  betas: [0.9,0.999]
  weight_decay: 0.0
  lr: 0.0002
checkpoint:
  - type: huggingface
    save_every_n_epochs: 1
    output_dir: /checkpoint/llama-3.1-swiftkv-405b-instruct
    save_end_of_training: true
