type: swiftkv
code: ../train.py
micro_batch_size: 1
epochs: 1
gradient_accumulation_steps: 1
temperature: 2.0
model:
  name_or_path: /checkpoint/aqiao/swiftkv-long/llama-3.1-swiftkv-8b-instruct-long-12-phase1-fix/global_step_5016
  num_key_value_layers: 16
  key_value_group_size: 1
  attn_implementation: flash_attention_2
deepspeed:
  zero_optimization:
    stage: 3
data:
  sources:
    - type: lmsys/lmsys-chat-1m
      name_or_path: lmsys/lmsys-chat-1m
      sample_count: 1000000
    - type: nvidia/AceMath-Instruct-Training-Data
      name_or_path: nvidia/AceMath-Instruct-Training-Data
      split: general_sft_stage2
      sample_count: 1000000
    - THUDM/LongAlign-10k
    - Yukang/LongAlpaca-12k
  use_data_cache: false
  cache_processed_data: true
  cache_dir: /data-fast/data-cache
  num_proc: 16
  max_length: 32768
logger:
  level: INFO
  output_dir: "./"
  file_output_ranks: [0]
scheduler:
  warmup_ratio: 0.05
optimizer:
  betas: [0.9,0.999]
  weight_decay: 0.0
  lr: 0.0002
checkpoint:
  - type: huggingface
    save_every_n_epochs: 1
    output_dir: /checkpoint/aqiao/swiftkv-long/llama-3.1-swiftkv-8b-instruct-long-12-phase2d
    save_end_of_training: true
