type: swiftkv
code: ../train.py
micro_batch_size: 1
epochs: 1
gradient_accumulation_steps: 1
logits_loss_temp: 2.0
#hidden_loss_mult: 1.0
#hidden_loss_layer: -8
model:
  name_or_path: Qwen/Qwen3-8B
  num_key_value_layers: 14
  key_value_group_size: 1
  attn_implementation: flash_attention_2
deepspeed:
  zero_optimization:
    stage: 2
data:
  sources:
    - type: nvidia/AceMath-Instruct-Training-Data
      name_or_path: nvidia/AceMath-Instruct-Training-Data
      split: general_sft_stage2
      sample_count: 500000
      kwargs:
        verification_mode: no_checks
    - HuggingFaceH4/ultrachat_200k
    - Open-Orca/SlimOrca
  use_data_cache: true
  cache_processed_data: true
  cache_dir: /data/data-cache
  num_proc: 16
  max_length: 8192
  mask_inputs: true
logger:
  level: INFO
  output_dir: "./"
  file_output_ranks: [0]
scheduler:
  warmup_ratio: 0.05
optimizer:
  betas: [0.9,0.999]
  weight_decay: 0.0
  lr: 0.0002
checkpoint:
  - type: huggingface
    save_every_n_epochs: 1
    output_dir: /checkpoint/aqiao/qwen3-swiftkv-8b-instruct
    save_end_of_training: true
