type: dpo
micro_batch_size: 1
epochs: 1
gradient_accumulation_steps: 2
beta: 0.1
model:
  name_or_path: meta-llama/Llama-3.1-8B-Instruct
ref_model:
  name_or_path: meta-llama/Llama-3.1-8B-Instruct
deepspeed:
  zero_optimization:
    stage: 3
data:
  sources:
    - HuggingFaceH4/ultrafeedback_binarized
  use_data_cache: true
  cache_processed_data: true
  cache_dir: /data/data-cache
  num_proc: 16
  max_length: 8192
logger:
  level: WARNING
  output_dir: "./"
  file_output_ranks: [0]
scheduler:
  warmup_ratio: 0.05
optimizer:
  betas: [0.9,0.999]
  weight_decay: 0.0
  lr: 0.0002
checkpoint:
  - type: huggingface
    save_every_n_steps: 10000
    output_dir: /data/dpo-llama-8b
    save_end_of_training: true
