name: GPU CI (Modal)

# This CI is running on modal.com's GPUs.
#
# It's set up here on github actions and then the cloned repo is sent to modal and everything
# happens on their hw - see ci/torch_latest.py  for where the actual vm is loaded, updated and the tests are
# run.
#
# Both files are annotated to what's important and how one might change or update things if needed.
#
# Note that since this is a Required job we can't use `on.push.path` file filter - we are using
# collect-tests job to do the filtering for us so that the job can be skipped and satisfy the
# Required status for PRs to pass.
#

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# on:
#   workflow_dispatch:

#   push:
#     branches:
#       - main

#   pull_request_target:
#     # XXX: re-enable later when workflow is working
#     # paths:
#     #   - '**.py'
#     paths-ignore:
#       - 'docs/**'
#       - 'projects/**'
#       - 'scripts/**'
#       - 'tutorial/**'
#     types: [review_requested, ready_for_review, synchronize]
#     branches:
#       - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  collect-tests:
    name: Collect tests to run
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      arctictraining: ${{ steps.filter.outputs.arctictraining }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Filter changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            arctictraining:
              - 'arctictraining/**'
              - '.github/workflows/modal*.yml'
              - 'ci/**'
              - 'tests/**'

  deploy:
    name: ArcticTraining CI
    runs-on: ubuntu-latest
    needs: collect-tests
    env:
      # note: we are sharing the same account with deepspeedai
      # XXX: none of the below is still set up
      # these are created at https://modal.com/settings/deepspeedai/tokens
      # they are then added to the repo's secrets at https://github.com/snowflakedb/ArcticTraining/settings/secrets/actions
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      # this one comes from https://huggingface.co/settings/profile of the bot user
      # and it too is then updated at https://github.com/snowflakedb/ArcticTraining/settings/secrets/actions
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    if: needs.collect-tests.outputs.arctictraining == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip' # caching pip dependencies

      - name: Install build dependencies
        run: |
          pip install uv # much faster than pip
          uv pip install --system modal
          # this helps to cache the packages w/o rebuilding the modal image on each run
          uv pip compile pyproject.toml --extra testing -o ci-requirements.txt
          # add any soft deps not listed in pyproject.toml here
          echo 'flash_attn' >> ci-requirements2.txt

      - name: Run tests
        run: |
          modal run -m ci.torch_latest
